Repository WitchyCat/Enfaria, pull requests merged in 2021-02, with the labels that each got.

#68 Fixes `getversion` return type
  enfaria-web/Cargo.toml
  enfaria-web/src/api.rs
  enfaria-web/src/template.rs
Labels: Fix

#69 Game updater prototype
  .env
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  README.md
  check.sh
  enfaria-game/.env
  enfaria-game/export_presets.cfg
  enfaria-game/src/menu/mainmenu.gd
  enfaria-updater/Cargo.toml
  enfaria-updater/rustfmt.toml
  enfaria-updater/src/main.rs
  enfaria-web/src/api.rs
  enfaria-web/src/index.rs
  enfaria-web/src/main.rs
  enfaria-web/src/release.rs
  native.sh
  scripts/database.sh
  scripts/native.sh
  scripts/schema.sql
Labels: Feature

#70 Add setup script to increase ease of development
  .gitignore
  README.md
  scripts/release.sh
Labels: QoL

#71 Cleans up Godot code
  enfaria-game/addons/gut/gut_cmdln.gd
  enfaria-game/project.godot
  enfaria-game/src/game.gd
  enfaria-game/src/global/connection.gd
  enfaria-game/src/menu/controls.gd
  enfaria-game/src/menu/mainmenu.gd
  enfaria-game/src/menu/options.gd
  enfaria-game/src/objects/object.gd
  enfaria-game/src/objects/plant.gd
  enfaria-game/src/tiles/tile.gd
  enfaria-game/src/ui/chat.gd
  enfaria-game/src/ui/inventory.gd
  enfaria-game/src/ui/pause.gd
  enfaria-game/src/ui/pause.tscn
  enfaria-game/src/ui/slot.gd
Labels: Code Improvement

#73 Fix so it runs on Linux
  enfaria-game/project.godot
  enfaria-game/src/game.gd
  enfaria-game/src/global/connection.gd
  scripts/database.sh
  scripts/native.sh
  scripts/release.sh
Labels: Fix

#74 Better tide error handling
  enfaria-web/src/error.rs
  enfaria-web/src/main.rs
  enfaria-web/src/prelude.rs
  enfaria-web/src/register.rs
  enfaria-web/src/template.rs
  enfaria-web/templates/index.tera
  enfaria-web/templates/login.tera
  enfaria-web/templates/register.tera
Labels: Feature

#76 Replace ggez with tetra
  .github/workflows/rust.yml
  Cargo.lock
  SDL2.dll
  SDL2.lib
  enfaria-game/Cargo.toml
  enfaria-game/src/egui.rs
  enfaria-game/src/main.rs
  enfaria-game/src/scenes.rs
  enfaria-game/src/scenes/game.rs
  enfaria-game/src/scenes/menu.rs
  enfaria-game/src/state.rs
  enfaria-game/src/world.rs
Labels: Code Improvement, Refactor

#77 Login screen and networking
  Cargo.lock
  enfaria-common/Cargo.toml
  enfaria-common/src/components/drawable.rs
  enfaria-common/src/components/mod.rs
  enfaria-common/src/components/sync.rs
  enfaria-common/src/lib.rs
  enfaria-common/src/message.rs
  enfaria-common/src/packet.rs
  enfaria-common/src/state.rs
  enfaria-common/src/systems/mod.rs
  enfaria-common/src/systems/render.rs
  enfaria-game/Cargo.toml
  enfaria-game/src/egui.rs
  enfaria-game/src/main.rs
  enfaria-game/src/networking.rs
  enfaria-game/src/scenes.rs
  enfaria-game/src/scenes/game.rs
  enfaria-game/src/scenes/menu.rs
  enfaria-game/src/state.rs
  enfaria-game/src/world.rs
  enfaria-server/Cargo.toml
  enfaria-server/src/connect.rs
  enfaria-server/src/data.rs
  enfaria-server/src/main.rs
  enfaria-server/src/prelude.rs
  enfaria-server/src/server.rs
  enfaria-server/src/tick.rs
Labels: Feature
