Repository WitchyCat/Enfaria, pull requests merged in 2021-03, with the labels that each got.

#80 Render with z-index properly
  src/systems/render.rs
Labels: Fix

#82 Adds pause scene and improves UI positioning
  src/main.rs
  src/scenes.rs
  src/scenes/game.rs
  src/scenes/menu.rs
  src/scenes/pause.rs
  src/utils/mod.rs
  src/utils/screen.rs
Labels: Code Improvement, Feature

#81 Adds map deserialization test
  src/data/map.rs
Labels: Code Improvement

#83 Add back button to options scene
  src/scenes/menu.rs
  src/scenes/options.rs
Labels: Feature
